"""removed user from category

Revision ID: 18a5a07037e8
Revises: 1ba999287725
Create Date: 2026-04-27 21:35:47.443514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18a5a07037e8'
down_revision: Union[str, Sequence[str], None] = '1ba999287725'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categories', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(op.f('fk_categories_created_by'), 'categories', type_='foreignkey')
    op.drop_column('categories', 'created_by')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('fk_categories_created_by'), 'categories', 'users', ['created_by'], ['id'])
    op.alter_column('categories', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
