"""add new field to table

Revision ID: 1ba999287725
Revises: a51c398e688e
Create Date: 2026-04-27 12:13:37.621484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ba999287725'
down_revision: Union[str, Sequence[str], None] = 'a51c398e688e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'dept')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('dept', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
